### ISSUE TITLE
Refactor DiscordGateway2HttpMaster to Maven Project Structure

### ISSUE THREAD

**Issue by moflwi** [plengauer/Philbot#77]
#### What
The current code structure in the Dockerfile is not following best practices and is considered an anti-pattern. The comment # this is super anti-pattern, fix with a proper maven project suggests that the project should be refactored to adhere to a proper Maven project structure.

#### Where
https://github.com/plengauer/Philbot/blob/main/DiscordGateway2HTTPMaster/Dockerfile#L4

#### Acceptance Criteria
* The Dockerfile should reflect the updated Maven project structure.
* The project should build and run successfully with the new Maven structure.
* The maven project should work seamlessly with Renovate.

**Comment by plengauer** [comment]
I think another requirement should be that it will still work with renovate (including the manual version bump thats in the github actions)
